var searchData=
[
  ['cacheadapter',['CacheAdapter',['../da/d10/interfacecom_1_1mysql_1_1cj_1_1_cache_adapter.html',1,'com::mysql::cj']]],
  ['cacheadapter_3c_20string_2c_20com_3a_3amysql_3a_3acj_3a_3aparseinfo_20_3e',['CacheAdapter&lt; String, com::mysql::cj::ParseInfo &gt;',['../da/d10/interfacecom_1_1mysql_1_1cj_1_1_cache_adapter.html',1,'com::mysql::cj']]],
  ['cacheadapter_3c_20string_2c_20map_3c_20string_2c_20string_20_3e_20_3e',['CacheAdapter&lt; String, Map&lt; String, String &gt; &gt;',['../da/d10/interfacecom_1_1mysql_1_1cj_1_1_cache_adapter.html',1,'com::mysql::cj']]],
  ['cacheadapter_3c_20string_2c_20parseinfo_20_3e',['CacheAdapter&lt; String, ParseInfo &gt;',['../da/d10/interfacecom_1_1mysql_1_1cj_1_1_cache_adapter.html',1,'com::mysql::cj']]],
  ['cacheadapterfactory',['CacheAdapterFactory',['../d3/dce/interfacecom_1_1mysql_1_1cj_1_1_cache_adapter_factory.html',1,'com::mysql::cj']]],
  ['cacheadapterfactory_3c_20string_2c_20map_3c_20string_2c_20string_20_3e_20_3e',['CacheAdapterFactory&lt; String, Map&lt; String, String &gt; &gt;',['../d3/dce/interfacecom_1_1mysql_1_1cj_1_1_cache_adapter_factory.html',1,'com::mysql::cj']]],
  ['cacheadapterfactory_3c_20string_2c_20parseinfo_20_3e',['CacheAdapterFactory&lt; String, ParseInfo &gt;',['../d3/dce/interfacecom_1_1mysql_1_1cj_1_1_cache_adapter_factory.html',1,'com::mysql::cj']]],
  ['cachedresultsetmetadata',['CachedResultSetMetaData',['../d1/d6d/interfacecom_1_1mysql_1_1cj_1_1jdbc_1_1result_1_1_cached_result_set_meta_data.html',1,'com::mysql::cj::jdbc::result']]],
  ['cachedresultsetmetadataimpl',['CachedResultSetMetaDataImpl',['../d2/d55/classcom_1_1mysql_1_1cj_1_1jdbc_1_1result_1_1_cached_result_set_meta_data_impl.html',1,'com::mysql::cj::jdbc::result']]],
  ['cachedrowsettest',['CachedRowsetTest',['../d6/dd7/classtestsuite_1_1regression_1_1_cached_rowset_test.html',1,'testsuite::regression']]],
  ['cachingsha2passwordplugin',['CachingSha2PasswordPlugin',['../d4/dfc/classcom_1_1mysql_1_1cj_1_1protocol_1_1a_1_1authentication_1_1_caching_sha2_password_plugin.html',1,'com::mysql::cj::protocol::a::authentication']]],
  ['callablestatement',['CallableStatement',['../da/dbe/classcom_1_1mysql_1_1cj_1_1jdbc_1_1_callable_statement.html',1,'com::mysql::cj::jdbc']]],
  ['callablestatementparaminfo',['CallableStatementParamInfo',['../d9/d87/classcom_1_1mysql_1_1cj_1_1jdbc_1_1_callable_statement_1_1_callable_statement_param_info.html',1,'com::mysql::cj::jdbc::CallableStatement']]],
  ['callablestatementregressiontest',['CallableStatementRegressionTest',['../d2/dab/classtestsuite_1_1regression_1_1_callable_statement_regression_test.html',1,'testsuite::regression']]],
  ['callablestatementtest',['CallableStatementTest',['../da/d5c/classtestsuite_1_1simple_1_1_callable_statement_test.html',1,'testsuite::simple']]],
  ['callablestatementwrapper',['CallableStatementWrapper',['../d2/dc7/classcom_1_1mysql_1_1cj_1_1jdbc_1_1_callable_statement_wrapper.html',1,'com::mysql::cj::jdbc']]],
  ['cancelquerytask',['CancelQueryTask',['../d2/dc5/interfacecom_1_1mysql_1_1cj_1_1_cancel_query_task.html',1,'com::mysql::cj']]],
  ['cancelquerytaskimpl',['CancelQueryTaskImpl',['../d3/dc3/classcom_1_1mysql_1_1cj_1_1_cancel_query_task_impl.html',1,'com::mysql::cj']]],
  ['cancelstatus',['CancelStatus',['../d0/d61/enumcom_1_1mysql_1_1cj_1_1_query_1_1_cancel_status.html',1,'com::mysql::cj::Query']]],
  ['capabilitiesgetorbuilder',['CapabilitiesGetOrBuilder',['../d0/da8/interfacecom_1_1mysql_1_1cj_1_1x_1_1protobuf_1_1_mysqlx_connection_1_1_capabilities_get_or_builder.html',1,'com::mysql::cj::x::protobuf::MysqlxConnection']]],
  ['capabilitiesorbuilder',['CapabilitiesOrBuilder',['../dc/ddd/interfacecom_1_1mysql_1_1cj_1_1x_1_1protobuf_1_1_mysqlx_connection_1_1_capabilities_or_builder.html',1,'com::mysql::cj::x::protobuf::MysqlxConnection']]],
  ['capabilitiessetorbuilder',['CapabilitiesSetOrBuilder',['../d5/d2f/interfacecom_1_1mysql_1_1cj_1_1x_1_1protobuf_1_1_mysqlx_connection_1_1_capabilities_set_or_builder.html',1,'com::mysql::cj::x::protobuf::MysqlxConnection']]],
  ['capabilityorbuilder',['CapabilityOrBuilder',['../da/d18/interfacecom_1_1mysql_1_1cj_1_1x_1_1protobuf_1_1_mysqlx_connection_1_1_capability_or_builder.html',1,'com::mysql::cj::x::protobuf::MysqlxConnection']]],
  ['changemode',['ChangeMode',['../db/d19/enumcom_1_1mysql_1_1cj_1_1xdevapi_1_1_foreign_key_definition_1_1_change_mode.html',1,'com::mysql::cj::xdevapi::ForeignKeyDefinition']]],
  ['charsetmapping',['CharsetMapping',['../d3/db7/classcom_1_1mysql_1_1cj_1_1_charset_mapping.html',1,'com::mysql::cj']]],
  ['charsetregressiontest',['CharsetRegressionTest',['../db/db3/classtestsuite_1_1regression_1_1_charset_regression_test.html',1,'testsuite::regression']]],
  ['charsettest',['CharsetTest',['../db/d4c/classtestsuite_1_1simple_1_1_charset_test.html',1,'testsuite::simple']]],
  ['cjcommunicationsexception',['CJCommunicationsException',['../dd/d16/classcom_1_1mysql_1_1cj_1_1exceptions_1_1_c_j_communications_exception.html',1,'com::mysql::cj::exceptions']]],
  ['cjconnectionfeaturenotavailableexception',['CJConnectionFeatureNotAvailableException',['../de/db1/classcom_1_1mysql_1_1cj_1_1exceptions_1_1_c_j_connection_feature_not_available_exception.html',1,'com::mysql::cj::exceptions']]],
  ['cjexception',['CJException',['../df/dac/classcom_1_1mysql_1_1cj_1_1exceptions_1_1_c_j_exception.html',1,'com::mysql::cj::exceptions']]],
  ['cjoperationnotsupportedexception',['CJOperationNotSupportedException',['../d9/d6f/classcom_1_1mysql_1_1cj_1_1exceptions_1_1_c_j_operation_not_supported_exception.html',1,'com::mysql::cj::exceptions']]],
  ['cjpackettoobigexception',['CJPacketTooBigException',['../dd/d74/classcom_1_1mysql_1_1cj_1_1exceptions_1_1_c_j_packet_too_big_exception.html',1,'com::mysql::cj::exceptions']]],
  ['cjtimeoutexception',['CJTimeoutException',['../d8/d82/classcom_1_1mysql_1_1cj_1_1exceptions_1_1_c_j_timeout_exception.html',1,'com::mysql::cj::exceptions']]],
  ['clientinfoprovider',['ClientInfoProvider',['../d1/d1b/interfacecom_1_1mysql_1_1cj_1_1jdbc_1_1_client_info_provider.html',1,'com::mysql::cj::jdbc']]],
  ['clientinfoprovidersp',['ClientInfoProviderSP',['../d5/d5f/classcom_1_1mysql_1_1cj_1_1jdbc_1_1_client_info_provider_s_p.html',1,'com::mysql::cj::jdbc']]],
  ['clientmessagesorbuilder',['ClientMessagesOrBuilder',['../d1/d0d/interfacecom_1_1mysql_1_1cj_1_1x_1_1protobuf_1_1_mysqlx_1_1_client_messages_or_builder.html',1,'com::mysql::cj::x::protobuf::Mysqlx']]],
  ['clientpreparedquery',['ClientPreparedQuery',['../d1/ddc/classcom_1_1mysql_1_1cj_1_1_client_prepared_query.html',1,'com::mysql::cj']]],
  ['clientpreparedquerybindings',['ClientPreparedQueryBindings',['../d8/dcf/classcom_1_1mysql_1_1cj_1_1_client_prepared_query_bindings.html',1,'com::mysql::cj']]],
  ['clientpreparedquerybindvalue',['ClientPreparedQueryBindValue',['../d9/d43/classcom_1_1mysql_1_1cj_1_1_client_prepared_query_bind_value.html',1,'com::mysql::cj']]],
  ['clientpreparedstatement',['ClientPreparedStatement',['../d4/dc9/classcom_1_1mysql_1_1cj_1_1jdbc_1_1_client_prepared_statement.html',1,'com::mysql::cj::jdbc']]],
  ['clob',['Clob',['../d1/d57/classcom_1_1mysql_1_1cj_1_1jdbc_1_1_clob.html',1,'com::mysql::cj::jdbc']]],
  ['closedonexpiredpasswordexception',['ClosedOnExpiredPasswordException',['../d8/d41/classcom_1_1mysql_1_1cj_1_1exceptions_1_1_closed_on_expired_password_exception.html',1,'com::mysql::cj::exceptions']]],
  ['closeorbuilder',['CloseOrBuilder',['../df/d3f/interfacecom_1_1mysql_1_1cj_1_1x_1_1protobuf_1_1_mysqlx_connection_1_1_close_or_builder.html',1,'com.mysql.cj.x.protobuf.MysqlxConnection.CloseOrBuilder'],['../d0/d86/interfacecom_1_1mysql_1_1cj_1_1x_1_1protobuf_1_1_mysqlx_session_1_1_close_or_builder.html',1,'com.mysql.cj.x.protobuf.MysqlxSession.CloseOrBuilder'],['../d4/d88/interfacecom_1_1mysql_1_1cj_1_1x_1_1protobuf_1_1_mysqlx_expect_1_1_close_or_builder.html',1,'com.mysql.cj.x.protobuf.MysqlxExpect.CloseOrBuilder']]],
  ['collection',['Collection',['../d1/dfe/interfacecom_1_1mysql_1_1cj_1_1xdevapi_1_1_collection.html',1,'com::mysql::cj::xdevapi']]],
  ['collectionaddtest',['CollectionAddTest',['../df/d4c/classtestsuite_1_1x_1_1devapi_1_1_collection_add_test.html',1,'testsuite::x::devapi']]],
  ['collectionfindtest',['CollectionFindTest',['../d8/dbb/classtestsuite_1_1x_1_1devapi_1_1_collection_find_test.html',1,'testsuite::x::devapi']]],
  ['collectionimpl',['CollectionImpl',['../dd/d9c/classcom_1_1mysql_1_1cj_1_1xdevapi_1_1_collection_impl.html',1,'com::mysql::cj::xdevapi']]],
  ['collectionmodifytest',['CollectionModifyTest',['../dc/d44/classtestsuite_1_1x_1_1devapi_1_1_collection_modify_test.html',1,'testsuite::x::devapi']]],
  ['collectionorbuilder',['CollectionOrBuilder',['../d1/d21/interfacecom_1_1mysql_1_1cj_1_1x_1_1protobuf_1_1_mysqlx_crud_1_1_collection_or_builder.html',1,'com::mysql::cj::x::protobuf::MysqlxCrud']]],
  ['collectionremovetest',['CollectionRemoveTest',['../d2/d62/classtestsuite_1_1x_1_1devapi_1_1_collection_remove_test.html',1,'testsuite::x::devapi']]],
  ['collectiontest',['CollectionTest',['../d4/d8f/classtestsuite_1_1x_1_1devapi_1_1_collection_test.html',1,'testsuite::x::devapi']]],
  ['column',['Column',['../d5/dbe/interfacecom_1_1mysql_1_1cj_1_1xdevapi_1_1_column.html',1,'com::mysql::cj::xdevapi']]],
  ['columndef',['ColumnDef',['../d4/d86/classcom_1_1mysql_1_1cj_1_1xdevapi_1_1_column_def.html',1,'com::mysql::cj::xdevapi']]],
  ['columndefinition',['ColumnDefinition',['../d0/da9/interfacecom_1_1mysql_1_1cj_1_1xdevapi_1_1_column_definition.html',1,'com.mysql.cj.xdevapi.ColumnDefinition&lt; T extends ColumnDefinition&lt; T &gt;'],['../dc/d0d/interfacecom_1_1mysql_1_1cj_1_1protocol_1_1_column_definition.html',1,'com.mysql.cj.protocol.ColumnDefinition']]],
  ['columndefinition_3c_20generatedcolumndefinition_20_3e',['ColumnDefinition&lt; GeneratedColumnDefinition &gt;',['../dc/d0d/interfacecom_1_1mysql_1_1cj_1_1protocol_1_1_column_definition.html',1,'com::mysql::cj::protocol']]],
  ['columndefinition_3c_20staticcolumndefinition_20_3e',['ColumnDefinition&lt; StaticColumnDefinition &gt;',['../dc/d0d/interfacecom_1_1mysql_1_1cj_1_1protocol_1_1_column_definition.html',1,'com::mysql::cj::protocol']]],
  ['columndefinition_3c_20t_20_3e',['ColumnDefinition&lt; T &gt;',['../dc/d0d/interfacecom_1_1mysql_1_1cj_1_1protocol_1_1_column_definition.html',1,'com::mysql::cj::protocol']]],
  ['columndefinitionfactory',['ColumnDefinitionFactory',['../de/dd2/classcom_1_1mysql_1_1cj_1_1protocol_1_1a_1_1_column_definition_factory.html',1,'com::mysql::cj::protocol::a']]],
  ['columndefinitionreader',['ColumnDefinitionReader',['../dd/dab/classcom_1_1mysql_1_1cj_1_1protocol_1_1a_1_1_column_definition_reader.html',1,'com::mysql::cj::protocol::a']]],
  ['columnidentifierorbuilder',['ColumnIdentifierOrBuilder',['../d6/dd8/interfacecom_1_1mysql_1_1cj_1_1x_1_1protobuf_1_1_mysqlx_expr_1_1_column_identifier_or_builder.html',1,'com::mysql::cj::x::protobuf::MysqlxExpr']]],
  ['columnimpl',['ColumnImpl',['../db/d4d/classcom_1_1mysql_1_1cj_1_1xdevapi_1_1_column_impl.html',1,'com::mysql::cj::xdevapi']]],
  ['columnmetadataorbuilder',['ColumnMetaDataOrBuilder',['../d9/d29/interfacecom_1_1mysql_1_1cj_1_1x_1_1protobuf_1_1_mysqlx_resultset_1_1_column_meta_data_or_builder.html',1,'com::mysql::cj::x::protobuf::MysqlxResultset']]],
  ['columnorbuilder',['ColumnOrBuilder',['../d7/d7b/interfacecom_1_1mysql_1_1cj_1_1x_1_1protobuf_1_1_mysqlx_crud_1_1_column_or_builder.html',1,'com::mysql::cj::x::protobuf::MysqlxCrud']]],
  ['commentclientinfoprovider',['CommentClientInfoProvider',['../d8/d34/classcom_1_1mysql_1_1cj_1_1jdbc_1_1_comment_client_info_provider.html',1,'com::mysql::cj::jdbc']]],
  ['commonchecks',['CommonChecks',['../d7/d9e/classinstrumentation_1_1_common_checks.html',1,'instrumentation']]],
  ['communicationsexception',['CommunicationsException',['../d9/d5f/classcom_1_1mysql_1_1cj_1_1jdbc_1_1exceptions_1_1_communications_exception.html',1,'com::mysql::cj::jdbc::exceptions']]],
  ['comparable',['Comparable',['../d3/d10/class_comparable.html',1,'']]],
  ['comparablewrapper',['ComparableWrapper',['../d8/d26/classcom_1_1mysql_1_1cj_1_1jdbc_1_1_database_meta_data_1_1_comparable_wrapper.html',1,'com::mysql::cj::jdbc::DatabaseMetaData']]],
  ['compressedinputstream',['CompressedInputStream',['../d4/dd8/classcom_1_1mysql_1_1cj_1_1protocol_1_1a_1_1_compressed_input_stream.html',1,'com::mysql::cj::protocol::a']]],
  ['compressedpacketsender',['CompressedPacketSender',['../d2/d3e/classcom_1_1mysql_1_1cj_1_1protocol_1_1a_1_1_compressed_packet_sender.html',1,'com::mysql::cj::protocol::a']]],
  ['compressedpacketsendertest',['CompressedPacketSenderTest',['../d6/dc6/classcom_1_1mysql_1_1cj_1_1protocol_1_1a_1_1_compressed_packet_sender_test.html',1,'com::mysql::cj::protocol::a']]],
  ['concurrency',['Concurrency',['../d5/d43/enumcom_1_1mysql_1_1cj_1_1protocol_1_1_resultset_1_1_concurrency.html',1,'com::mysql::cj::protocol::Resultset']]],
  ['conditionoperation',['ConditionOperation',['../d9/d60/enumcom_1_1mysql_1_1cj_1_1x_1_1protobuf_1_1_mysqlx_expect_1_1_open_1_1_condition_1_1_condition_operation.html',1,'com::mysql::cj::x::protobuf::MysqlxExpect::Open::Condition']]],
  ['conditionorbuilder',['ConditionOrBuilder',['../d4/df8/interfacecom_1_1mysql_1_1cj_1_1x_1_1protobuf_1_1_mysqlx_expect_1_1_open_1_1_condition_or_builder.html',1,'com::mysql::cj::x::protobuf::MysqlxExpect::Open']]],
  ['connectionerrorfiringinvocationhandler',['ConnectionErrorFiringInvocationHandler',['../d1/dfd/classcom_1_1mysql_1_1cj_1_1jdbc_1_1_wrapper_base_1_1_connection_error_firing_invocation_handler.html',1,'com::mysql::cj::jdbc::WrapperBase']]],
  ['connectionfeaturenotavailableexception',['ConnectionFeatureNotAvailableException',['../db/d7d/classcom_1_1mysql_1_1cj_1_1jdbc_1_1exceptions_1_1_connection_feature_not_available_exception.html',1,'com::mysql::cj::jdbc::exceptions']]],
  ['connectiongroup',['ConnectionGroup',['../d2/de5/classcom_1_1mysql_1_1cj_1_1jdbc_1_1_connection_group.html',1,'com::mysql::cj::jdbc']]],
  ['connectiongroupmanager',['ConnectionGroupManager',['../d2/dbd/classcom_1_1mysql_1_1cj_1_1jdbc_1_1_connection_group_manager.html',1,'com::mysql::cj::jdbc']]],
  ['connectionimpl',['ConnectionImpl',['../d1/d2b/classcom_1_1mysql_1_1cj_1_1jdbc_1_1_connection_impl.html',1,'com::mysql::cj::jdbc']]],
  ['connectionisclosedexception',['ConnectionIsClosedException',['../dc/d08/classcom_1_1mysql_1_1cj_1_1exceptions_1_1_connection_is_closed_exception.html',1,'com::mysql::cj::exceptions']]],
  ['connectionlifecycleinterceptor',['ConnectionLifecycleInterceptor',['../d0/d8a/interfacecom_1_1mysql_1_1cj_1_1jdbc_1_1interceptors_1_1_connection_lifecycle_interceptor.html',1,'com::mysql::cj::jdbc::interceptors']]],
  ['connectionlistener',['ConnectionListener',['../da/d6e/classtestsuite_1_1regression_1_1_pooled_connection_regression_test_1_1_connection_listener.html',1,'testsuite::regression::PooledConnectionRegressionTest']]],
  ['connectionpropertiestransform',['ConnectionPropertiesTransform',['../d4/d8a/interfacecom_1_1mysql_1_1cj_1_1conf_1_1_connection_properties_transform.html',1,'com::mysql::cj::conf']]],
  ['connectionregressiontest',['ConnectionRegressionTest',['../df/df8/classtestsuite_1_1regression_1_1_connection_regression_test.html',1,'testsuite::regression']]],
  ['connectiontest',['ConnectionTest',['../d4/df7/classtestsuite_1_1simple_1_1_connection_test.html',1,'testsuite::simple']]],
  ['connectionurl',['ConnectionUrl',['../d3/d5e/classcom_1_1mysql_1_1cj_1_1conf_1_1_connection_url.html',1,'com::mysql::cj::conf']]],
  ['connectionurlparser',['ConnectionUrlParser',['../d8/d7f/classcom_1_1mysql_1_1cj_1_1conf_1_1_connection_url_parser.html',1,'com::mysql::cj::conf']]],
  ['connectionwrapper',['ConnectionWrapper',['../de/db8/classcom_1_1mysql_1_1cj_1_1jdbc_1_1_connection_wrapper.html',1,'com::mysql::cj::jdbc']]],
  ['constants',['Constants',['../de/dfc/classcom_1_1mysql_1_1cj_1_1_constants.html',1,'com::mysql::cj']]],
  ['contenttype_5fbytes',['ContentType_BYTES',['../d8/dc9/enumcom_1_1mysql_1_1cj_1_1x_1_1protobuf_1_1_mysqlx_resultset_1_1_content_type___b_y_t_e_s.html',1,'com::mysql::cj::x::protobuf::MysqlxResultset']]],
  ['contenttype_5fdatetime',['ContentType_DATETIME',['../d5/deb/enumcom_1_1mysql_1_1cj_1_1x_1_1protobuf_1_1_mysqlx_resultset_1_1_content_type___d_a_t_e_t_i_m_e.html',1,'com::mysql::cj::x::protobuf::MysqlxResultset']]],
  ['controlorders',['ControlOrders',['../da/dd7/classcontrol_1_1_control_orders.html',1,'control']]],
  ['controlsegments',['ControlSegments',['../d8/d81/classcontrol_1_1_control_segments.html',1,'control']]],
  ['controlvehicles',['ControlVehicles',['../d2/dd9/classcontrol_1_1_control_vehicles.html',1,'control']]],
  ['coresession',['CoreSession',['../d6/d8c/classcom_1_1mysql_1_1cj_1_1_core_session.html',1,'com::mysql::cj']]],
  ['createindexparams',['CreateIndexParams',['../d6/d12/classcom_1_1mysql_1_1cj_1_1xdevapi_1_1_create_index_params.html',1,'com::mysql::cj::xdevapi']]],
  ['createvieworbuilder',['CreateViewOrBuilder',['../df/d02/interfacecom_1_1mysql_1_1cj_1_1x_1_1protobuf_1_1_mysqlx_crud_1_1_create_view_or_builder.html',1,'com::mysql::cj::x::protobuf::MysqlxCrud']]],
  ['ctxoperation',['CtxOperation',['../de/dfc/enumcom_1_1mysql_1_1cj_1_1x_1_1protobuf_1_1_mysqlx_expect_1_1_open_1_1_ctx_operation.html',1,'com::mysql::cj::x::protobuf::MysqlxExpect::Open']]]
];
